import Head from 'next/head'
import { useRouter } from 'next/router'

export default function Timer() {
  const { query } = useRouter() 

  console.log(query)

  return (
    <>
      <Head>
        <title>Timer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <span>{query.id}</span>
      </main>
    </>
  )
}
