import { CardTimer } from 'components/CardTimer'
import Header from 'components/Header'
import Head from 'next/head'

import * as S from '../styles/pages/home'

export default function Home () {
  return (
    <>
      <S.Container>
        <Head>
          <title>Cooker timer</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <S.Main>
          <section>
            <h1>Vamos começar a cozinhar?</h1>
            <p>Crie seu primeiro temporizador e defina seus horários.</p>
          </section>
          <section className="cardsGrid">
            <CardTimer
              type="edit"
              timer={{
                title: 'Fazendo arroz na panela'
              }}
            />
            <CardTimer type="add"/>
          </section>
        </S.Main>
      </S.Container>
    </>
  )
}
