import Head from 'next/head'
import Header from 'components/Header'
import * as S from '../styles/pages/home'

export default function Home() {
  return (
    <>
      <S.Container>
        <Head>
          <title>Cooker timer</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
      </S.Container>
    </>
  )
}
